// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_vgWgaBS7FV6A8-2GP5Jl6WUVjcxw1A',
    appId: '1:480126954908:web:6658cb3ecaf0322bb62c59',
    messagingSenderId: '480126954908',
    projectId: 'swap-shop-partner',
    authDomain: 'swap-shop-partner.firebaseapp.com',
    storageBucket: 'swap-shop-partner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuyeiPi9ZhfC1v8BFuDN_CZ4bdResBx1k',
    appId: '1:480126954908:android:5042f2c1bff9b704b62c59',
    messagingSenderId: '480126954908',
    projectId: 'swap-shop-partner',
    storageBucket: 'swap-shop-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgOdXIlUvezATdkMak5GuTGJ1QfkmtXg',
    appId: '1:480126954908:ios:6eaa5d07e518cd20b62c59',
    messagingSenderId: '480126954908',
    projectId: 'swap-shop-partner',
    storageBucket: 'swap-shop-partner.firebasestorage.app',
    iosBundleId: 'com.example.swapStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgOdXIlUvezATdkMak5GuTGJ1QfkmtXg',
    appId: '1:480126954908:ios:6eaa5d07e518cd20b62c59',
    messagingSenderId: '480126954908',
    projectId: 'swap-shop-partner',
    storageBucket: 'swap-shop-partner.firebasestorage.app',
    iosBundleId: 'com.example.swapStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI_vgWgaBS7FV6A8-2GP5Jl6WUVjcxw1A',
    appId: '1:480126954908:web:13b6428a66a61323b62c59',
    messagingSenderId: '480126954908',
    projectId: 'swap-shop-partner',
    authDomain: 'swap-shop-partner.firebaseapp.com',
    storageBucket: 'swap-shop-partner.firebasestorage.app',
  );
}
